# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/recommendation.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/recommendation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/recommendation.proto\x12\x0erecommendation\"\x83\x01\n\x10RecommendRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x16\n\x0ereal_estate_id\x18\x03 \x01(\t\x12\x10\n\x08latitude\x18\x04 \x01(\x01\x12\x11\n\tlongitude\x18\x05 \x01(\x01\x12\r\n\x05limit\x18\x0c \x01(\x05\";\n\x11RecommendResponse\x12\x14\n\x0cproperty_ids\x18\x01 \x03(\t\x12\x10\n\x08strategy\x18\x02 \x01(\t\"R\n\x0eViewedProperty\x12\x16\n\x0ereal_estate_id\x18\x01 \x01(\t\x12\x10\n\x08\x64uration\x18\x02 \x01(\x05\x12\x16\n\x0eviewed_at_unix\x18\x03 \x01(\x03\"\x7f\n\x11PrecomputeRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x34\n\x0cview_history\x18\x02 \x03(\x0b\x32\x1e.recommendation.ViewedProperty\x12\x10\n\x08latitude\x18\x03 \x01(\x01\x12\x11\n\tlongitude\x18\x04 \x01(\x01\"4\n\x12PrecomputeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x32\xce\x01\n\x15RecommendationService\x12Y\n\x12GetRecommendations\x12 .recommendation.RecommendRequest\x1a!.recommendation.RecommendResponse\x12Z\n\x11PrecomputeForUser\x12!.recommendation.PrecomputeRequest\x1a\".recommendation.PrecomputeResponseB;Z9recomendation_service/proto/recommendation;recommendationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.recommendation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9recomendation_service/proto/recommendation;recommendation'
  _globals['_RECOMMENDREQUEST']._serialized_start=47
  _globals['_RECOMMENDREQUEST']._serialized_end=178
  _globals['_RECOMMENDRESPONSE']._serialized_start=180
  _globals['_RECOMMENDRESPONSE']._serialized_end=239
  _globals['_VIEWEDPROPERTY']._serialized_start=241
  _globals['_VIEWEDPROPERTY']._serialized_end=323
  _globals['_PRECOMPUTEREQUEST']._serialized_start=325
  _globals['_PRECOMPUTEREQUEST']._serialized_end=452
  _globals['_PRECOMPUTERESPONSE']._serialized_start=454
  _globals['_PRECOMPUTERESPONSE']._serialized_end=506
  _globals['_RECOMMENDATIONSERVICE']._serialized_start=509
  _globals['_RECOMMENDATIONSERVICE']._serialized_end=715
# @@protoc_insertion_point(module_scope)
