# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import recommendation_pb2 as proto_dot_recommendation__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/recommendation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecommendationServiceStub:
    """Service cung cấp các API liên quan đến gợi ý bất động sản
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRecommendations = channel.unary_unary(
                '/recommendation.RecommendationService/GetRecommendations',
                request_serializer=proto_dot_recommendation__pb2.RecommendRequest.SerializeToString,
                response_deserializer=proto_dot_recommendation__pb2.RecommendResponse.FromString,
                _registered_method=True)
        self.PrecomputeForUser = channel.unary_unary(
                '/recommendation.RecommendationService/PrecomputeForUser',
                request_serializer=proto_dot_recommendation__pb2.PrecomputeRequest.SerializeToString,
                response_deserializer=proto_dot_recommendation__pb2.PrecomputeResponse.FromString,
                _registered_method=True)


class RecommendationServiceServicer:
    """Service cung cấp các API liên quan đến gợi ý bất động sản
    """

    def GetRecommendations(self, request, context):
        """Lấy danh sách gợi ý bất động sản cho người dùng (Real-time)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrecomputeForUser(self, request, context):
        """Tính toán trước danh sách gợi ý cho người dùng (Batch job)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommendationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommendations,
                    request_deserializer=proto_dot_recommendation__pb2.RecommendRequest.FromString,
                    response_serializer=proto_dot_recommendation__pb2.RecommendResponse.SerializeToString,
            ),
            'PrecomputeForUser': grpc.unary_unary_rpc_method_handler(
                    servicer.PrecomputeForUser,
                    request_deserializer=proto_dot_recommendation__pb2.PrecomputeRequest.FromString,
                    response_serializer=proto_dot_recommendation__pb2.PrecomputeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recommendation.RecommendationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recommendation.RecommendationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecommendationService:
    """Service cung cấp các API liên quan đến gợi ý bất động sản
    """

    @staticmethod
    def GetRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.RecommendationService/GetRecommendations',
            proto_dot_recommendation__pb2.RecommendRequest.SerializeToString,
            proto_dot_recommendation__pb2.RecommendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrecomputeForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.RecommendationService/PrecomputeForUser',
            proto_dot_recommendation__pb2.PrecomputeRequest.SerializeToString,
            proto_dot_recommendation__pb2.PrecomputeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
